Reduce JS size
miamtech/analyticsShared pull request #27
Opened 2024-09-13 13:55 UTC by antonin-francois

2024-09-13 13:55 UTC, antonin-francois commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/miamtech/analyticsShared/27?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#27** <a href="https://app.graphite.dev/github/pr/miamtech/analyticsShared/27?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#26** <a href="https://app.graphite.dev/github/pr/miamtech/analyticsShared/26?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `develop`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @antonin-francois and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-13 14:03 UTC, diarmuidmcg commented on analyticsShared/src/commonMain/kotlin/mealz/ai/AbstractSharedAnalytics.kt
> +//            abTestKey = abTestKey,
why commented?

2024-09-13 14:03 UTC, diarmuidmcg commented on analyticsShared/src/commonMain/kotlin/mealz/ai/AbstractSharedAnalytics.kt
> +//        }
?

2024-09-13 14:03 UTC, diarmuidmcg commented on analyticsShared/src/commonMain/kotlin/mealz/ai/Init.kt
> +//     SharedAnalytics.setAffiliate(affiliate)
?

2024-09-17 08:45 UTC, ThibaultMiam requested changes

2024-09-17 08:45 UTC, ThibaultMiam commented on analyticsShared/build.gradle.kts
> +    compilerOptions {
ça fait quoi ça ?

2024-09-17 08:45 UTC, ThibaultMiam commented on analyticsShared/src/androidMain/kotlin/mealz/ai/SharedAnalytics.android.kt
> +        install(DefaultRequest)
tu as besoin de la lib okHTTP pour android  ? je vois pas d'import

2024-09-17 08:45 UTC, ThibaultMiam commented on analyticsShared/src/androidMain/kotlin/mealz/ai/SharedAnalytics.android.kt
> +            setBody(jsonEvent)
il y a un intérêt a garder Gson dans un constante ou le jsonEvent ?

```suggestion
            setBody(Gson().toJson(event))
```

2024-09-17 08:45 UTC, ThibaultMiam commented on analyticsShared/src/androidMain/kotlin/mealz/ai/SharedAnalytics.android.kt
> +            httpClient.postEvent(event)
je pense que si on raccourci la fonction précédente on peut directement la mettre ici

2024-09-17 08:45 UTC, ThibaultMiam commented on analyticsShared/src/commonMain/kotlin/mealz/ai/AbstractSharedAnalytics.kt
> +        get() = this::domain.isInitialized && this::version.isInitialized && domain.isNotBlank() && version.isNotBlank()
pourquoi la moitié de champ on y accède avec un accesseur de classe et pas l'autre moitié  ?

2024-09-17 08:45 UTC, ThibaultMiam commented on analyticsShared/src/commonMain/kotlin/mealz/ai/AbstractSharedAnalytics.kt
> +        if (!alreadyInitialized) return
on devrais peut être rise un erreur si c'est la cas non ?

2024-09-17 08:45 UTC, ThibaultMiam commented on analyticsShared/src/commonMain/kotlin/mealz/ai/AbstractSharedAnalytics.kt
> +        internal const val PLAUSIBLE_URL: String = "https://plausible.io/api/event"
alors ça se convertie comment en js ?

2024-09-17 08:45 UTC, ThibaultMiam commented on analyticsShared/src/iosMain/kotlin/mealz/ai/SharedAnalytics.ios.kt
> +            httpClient.postEvent(event)
on a besoin de deux fonctions ?

2024-09-17 08:47 UTC, antonin-francois commented on analyticsShared/src/androidMain/kotlin/mealz/ai/SharedAnalytics.android.kt
> +            setBody(jsonEvent)
Très honnêtement je sais pas, j'ai suivi la doc

2024-09-17 08:50 UTC, antonin-francois commented on analyticsShared/src/iosMain/kotlin/mealz/ai/SharedAnalytics.ios.kt
> +            httpClient.postEvent(event)
bonne question, ktor est nouveau pour moi, j'ai copié collé le code existant

2024-09-17 08:51 UTC, antonin-francois commented on analyticsShared/src/androidMain/kotlin/mealz/ai/SharedAnalytics.android.kt
> +        install(DefaultRequest)
c'est pas ça `import io.ktor.client.plugins.DefaultRequest` ?

2024-09-17 08:53 UTC, antonin-francois commented on analyticsShared/src/commonMain/kotlin/mealz/ai/AbstractSharedAnalytics.kt
> +        get() = this::domain.isInitialized && this::version.isInitialized && domain.isNotBlank() && version.isNotBlank()
isInitialized n'est dispo qu'avec l'accesseur de classe

2024-09-17 08:53 UTC, antonin-francois commented on analyticsShared/src/commonMain/kotlin/mealz/ai/AbstractSharedAnalytics.kt
> +        if (!alreadyInitialized) return
à voir, ça peut être une solution mais j'ai pas forcément envie de faire crash l'app si le gars appelle 2 fois la méthode init 
peut-être simplement log une erreur ?

2024-09-17 08:57 UTC, antonin-francois commented on analyticsShared/build.gradle.kts
> +    compilerOptions {
c'est pour éviter que le linter rale sur les expect actual sur les classes

2024-09-17 09:05 UTC, ThibaultMiam commented on analyticsShared/src/androidMain/kotlin/mealz/ai/SharedAnalytics.android.kt
> +            setBody(jsonEvent)
bah c'est juset que quand tu créer une val tu a un adresse en mémoire , il y a moyen qu'a la compilation tout seul il te le vire , comme tu veux je pense que ça n'aporte pas plus d'info

2024-09-17 09:06 UTC, ThibaultMiam commented on analyticsShared/src/commonMain/kotlin/mealz/ai/AbstractSharedAnalytics.kt
> +        get() = this::domain.isInitialized && this::version.isInitialized && domain.isNotBlank() && version.isNotBlank()
ah pardon j'avais mal lu je pensai que tu testai tous les late init

2024-09-17 09:10 UTC, ThibaultMiam commented on analyticsShared/src/commonMain/kotlin/mealz/ai/AbstractSharedAnalytics.kt
> +        if (!alreadyInitialized) return
c'est pas quand analytic n'est pas init que ça crasherai ?

2024-09-17 09:13 UTC, ThibaultMiam commented on analyticsShared/src/iosMain/kotlin/mealz/ai/SharedAnalytics.ios.kt
> +            httpClient.postEvent(event)
je pense que ça fait le travail :
```suggestion
            httpClient. post(PLAUSIBLE_URL) {
            contentType(ContentType.Application.Json)
            setBody(plausibleEventToJson(event))
        }
```

2024-09-17 09:44 UTC, antonin-francois commented on analyticsShared/src/commonMain/kotlin/mealz/ai/AbstractSharedAnalytics.kt
> +        if (!alreadyInitialized) return
quand c'est pas init ça fait juste rien

2024-09-17 09:47 UTC, ThibaultMiam approved these changes

2024-09-17 09:48 UTC, merged